import { DecimalPipe, isPlatformBrowser } from '@angular/common';
import { Component, computed, inject, signal } from '@angular/core';
import { PLATFORM_ID } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { QuizService } from '../../../core/services/quiz.service';
import { ExamSubmission, Question, QuizEvaluationResult } from '../../../core/models/quiz.models';

@Component({
  imports: [DecimalPipe, RouterLink],
  selector: 'app-quiz-take',
  styleUrl: './quiz-take.css',
  templateUrl: './quiz-take.html',
})
export class QuizTake {

  private readonly route = inject(ActivatedRoute);
  private readonly auth = inject(AuthService);
  private readonly quizService = inject(QuizService);
  private readonly isBrowser = isPlatformBrowser(inject(PLATFORM_ID));
  private timerId?: ReturnType<typeof setInterval>;

  readonly quizId = signal<number>(0);
  readonly questions = signal<Question[]>([]);
  readonly currentQuestionIndex = signal<number>(0);
  readonly selectedAnswers = signal<Map<number, string>>(new Map());
  readonly isSubmitted = signal<boolean>(false);
  readonly result = signal<QuizEvaluationResult | null>(null);
  readonly loading = signal<boolean>(true);
  readonly submitting = signal<boolean>(false);
  readonly errorMessage = signal<string | null>(null);
  readonly answeredCount = computed(() => this.selectedAnswers().size);
  readonly secondsRemaining = signal(120);
  readonly timerLabel = computed(() => {
    const minutes = Math.floor(this.secondsRemaining() / 60).toString().padStart(2, '0');
    const seconds = (this.secondsRemaining() % 60).toString().padStart(2, '0');
    return `${minutes}:${seconds}`;
  });
  readonly timerIsUrgent = computed(() => this.secondsRemaining() <= 30);

  ngOnInit(): void {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    this.quizId.set(id);
    this.loadQuestions(id);
  }

  loadQuestions(id: number): void {
    this.loading.set(true);
    this.quizService.getQuestionsByQuiz(id).subscribe({
      next: (data) => {
        this.questions.set(data);
        this.loading.set(false);
        this.resetQuestionTimer();
      },
      error: () => this.loading.set(false)
    });
  }

  selectOption(questionId: number, option: string): void {
    if (this.isSubmitted()) return;
    const map = new Map(this.selectedAnswers());
    map.set(questionId, option);
    this.selectedAnswers.set(map);
  }

  goToQuestion(index: number): void {
    if (index < 0 || index >= this.questions().length || this.isSubmitted()) return;
    this.currentQuestionIndex.set(index);
    this.resetQuestionTimer();
  }

  submitExam(isAutomatic = false): void {
    if (this.submitting() || this.isSubmitted()) return;
    const user = this.auth.currentUser();
    if (!user?.username) {
      this.errorMessage.set('Your user session is missing a username. Please sign in again.');
      return;
    }

    if (!isAutomatic && this.selectedAnswers().size === 0) {
      this.errorMessage.set('Select at least one answer before submitting.');
      return;
    }

    const payload: ExamSubmission = {
      quizId: this.quizId(),
      username: user.username,
      userEmail: user.email,
      selectedAnswers: Object.fromEntries(this.selectedAnswers()),
    };

    this.submitting.set(true);
    this.stopQuestionTimer();
    this.errorMessage.set(null);
    this.quizService.evaluateQuiz(payload).subscribe({
      next: (evaluation) => {
        this.result.set(evaluation);
        this.isSubmitted.set(true);
        this.submitting.set(false);
      },
      error: (error) => {
        this.submitting.set(false);
        this.errorMessage.set(
          typeof error?.error === 'string'
            ? error.error
            : error?.error?.message || 'Unable to submit this assessment.'
        );
      },
    });
  }

  downloadResult(): void {
    const evaluation = this.result();
    const user = this.auth.currentUser();
    if (!evaluation || !this.isBrowser) return;

    const report = [
      'LEARNINGPURPOSE | ASSESSMENT REPORT',
      '====================================',
      `Learner: ${user?.username || 'Learner'}`,
      `Assessment: ${evaluation.quizTitle}`,
      `Status: ${evaluation.passed ? 'PASSED' : 'NOT PASSED'}`,
      '',
      'PERFORMANCE SUMMARY',
      '--------------------',
      `Percentage: ${evaluation.percentage}%`,
      `Marks scored: ${evaluation.marksScored} / ${evaluation.maxMarks}`,
      `Correct answers: ${evaluation.correctAnswers} / ${evaluation.totalQuestions}`,
      `Attempted: ${evaluation.attempted} / ${evaluation.totalQuestions}`,
      '',
      'Generated by LearningPurpose',
    ].join('\n');
    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${this.slugify(evaluation.quizTitle)}-result.txt`;
    link.click();
    URL.revokeObjectURL(url);
  }

  private slugify(value: string): string {
    return value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'assessment';
  }

  private resetQuestionTimer(): void {
    this.stopQuestionTimer();
    this.secondsRemaining.set(120);
    if (!this.isBrowser || this.isSubmitted()) return;
    this.timerId = setInterval(() => {
      if (this.secondsRemaining() <= 1) {
        this.secondsRemaining.set(0);
        this.stopQuestionTimer();
        this.submitExam(true);
        return;
      }
      this.secondsRemaining.update((seconds) => seconds - 1);
    }, 1000);
  }

  private stopQuestionTimer(): void {
    if (this.timerId) {
      clearInterval(this.timerId);
      this.timerId = undefined;
    }
  }

  ngOnDestroy(): void {
    this.stopQuestionTimer();
  }
}
